
homework = open('Homework.txt', 'r')
print(homework.read())
homework.close()

print()
print()
print()
print()
print()
print()
homework = open('Homework.txt', 'r')
print("\n Read in parts \n")
print(homework.read(8))
homework.close()
print()
print()
print()
print()
print()
print()
print()
homework = open('Homework.txt', 'r')
print("Reading first line...")
print(homework.readline())
homework.close()
print()
print()
print()
print()
print()
print()
homework = open('Homework.txt', 'r')
print("Looping through the lines...")
for line in homework:
    print(line)
homework.close()
print()
print()
print()
print()
print()
print()


homework1 = open('Homework.txt', 'r')
homework2 = open('HomeworkUpdated.txt', 'w')

for line in homework1.readlines():
    if not (line.startswith("Python")):
        print(line)
        homework2.write(line)

homework2.close()
homework1.close()